# docker-compose.yml
version: '3.8'
services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bolt"
      POSTGRES_DB: "prisma_db"

  backend:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:bolt@db:5432/prisma_db"

volumes: 
  data: {}
